// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLupmY_FOme9ZxoHgfvEI9_xYpQ4Ovz4E',
    appId: '1:263052277632:web:d869ea00d7a657fd8eb365',
    messagingSenderId: '263052277632',
    projectId: 'ssoma-app-b6c6c',
    authDomain: 'ssoma-app-b6c6c.firebaseapp.com',
    storageBucket: 'ssoma-app-b6c6c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiOF5C9JOqQzrIJ_1F5DHOiLUVhHW9AnA',
    appId: '1:263052277632:android:e22b6e4ba6243d768eb365',
    messagingSenderId: '263052277632',
    projectId: 'ssoma-app-b6c6c',
    storageBucket: 'ssoma-app-b6c6c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDa0Y7EGVvsR8w6PoSXqJbxNVxaSEj4Zb4',
    appId: '1:263052277632:ios:0530ae99a6630dc78eb365',
    messagingSenderId: '263052277632',
    projectId: 'ssoma-app-b6c6c',
    storageBucket: 'ssoma-app-b6c6c.firebasestorage.app',
    iosBundleId: 'com.example.ssomaApp',
  );
}
